name: mobex_kiosk
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

msix_config:
  display_name: Mobex Kiosk
  publisher_display_name: Mobility Exchange
  identity_name: company.mobility.exchange

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  shimmer: ^2.0.0
  timeago_flutter: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.4.0

  #Localization
  easy_localization: ^3.0.1
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  just_the_tooltip: ^0.0.12

  #Bloc supported plugins
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.3
  provider: ^6.0.3

  #Amplify
  amplify_api: ^1.0.1
  amplify_flutter: ^1.0.1
  amplify_auth_cognito: ^1.0.1
  amplify_storage_s3: ^1.0.1

  #  #Connectivity
  connectivity_plus: ^3.0.0
  battery_plus: ^2.1.4
  network_info_plus: ^2.1.3
#  flutter_reactive_ble: ^5.0.2
  wifi_scan: ^0.3.0
  connectivity_checker: ^1.1.0
  http: ^0.13.6
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.2

  #utils
  path_provider: ^2.0.10
  debug_logger: ^0.0.23
  flutter_secure_storage: ^5.0.2
  cached_network_image: ^3.2.1

  auto_route: ^4.0.1
  google_fonts: ^3.0.1
  animations: ^2.0.3
  csslib: 0.17.0
  formz: ^0.4.1
  tap_debouncer: ^2.0.2
  flutter_neumorphic: ^3.2.0
  rive: ^0.8.4

  #Multi Media/Webview supported plugins
  flutter_inappwebview: ^5.7.2+3
  internet_file: 1.2.0
#  pdfx: 2.2.0
  webview_flutter_plus: ^0.3.0+2
  webview_windows: ^0.2.2
  window_manager: ^0.3.6
#  syncfusion_flutter_pdfviewer: any
  easy_pdf_viewer: ^1.0.7
  advance_pdf_viewer2: ^2.0.5+1
  msix: ^3.16.4
  external_app_launcher: ^3.0.0
  simple_barcode_scanner:
    git:
      url: https://github.com/jainshashank7/simple_barcode_scanner.git
      ref: main

  qr_bar_code_scanner_dialog: ^0.0.5

  webdev: ^2.7.12

  #open other apps
  url_launcher: ^6.0.13
  url_launcher_windows: ^2.0.0
  wakelock: ^0.6.2
  flutter_screenutil: ^5.5.3+2
  in_app_notification: ^1.1.1
  video_player_win: ^2.3.4
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/langs/
    - assets/license/
    - assets/icons/
    - assets/animations/
    - assets/images/

